In [4]:
import numpy as np
my_list=np.array([1,2,3,4])
my_list

array([1, 2, 3, 4])

In [17]:
import numpy as np
a=np.ones((3,5))
print(a)
print(type(a))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
<class 'numpy.ndarray'>


In [123]:
np.random.seed(101) #to make the random samples consatnt 
arr=np.random.randint(0,100,(10)) # we want 10 random samples b/w 0 and 100
print(arr)


[95 11 81 70 63 87 75  9 77 40]


In [130]:
#numpy functions
arr.max()#finds maximum element of arr

7

In [132]:
arr.argmax()#finds index of maximum element of arr

0

In [131]:
arr.min()#finds minimum element of arr

9

In [133]:
arr.argmin()#finds index of minimum element of arr

7

In [136]:
arr.reshape(2,5) #give that dimension for which array could be splitted

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

In [137]:
arr.reshape(5,2) # reshape function help to convert in to different shape of different dimension

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

In [148]:
np.random.seed(101)
mat=np.random.randint(0,100,(10,10))
mat

array([[95, 11, 81, 70, 63, 87, 75,  9, 77, 40],
       [ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40],
       [49, 83,  8, 29, 59, 34, 44, 72, 19, 10],
       [76, 95, 87,  0, 73,  8, 62, 36, 83, 99],
       [28, 63,  7, 10, 52, 56, 38, 73, 52, 18],
       [71, 15, 44,  0, 12, 17, 75, 79, 97, 93],
       [24, 36, 63, 19, 35, 30, 10, 60, 20, 27],
       [ 8, 86, 26, 87, 46, 47, 54, 86,  9, 45],
       [ 2, 18, 58, 92, 11, 10, 94, 35, 28,  3],
       [83, 84, 47, 14, 69, 60, 69, 51,  6, 88]])

In [154]:
# mat[2,2]
 mat[2,0]# to access the element of matrix mat declared above

array([], shape=(0, 10), dtype=int32)

In [159]:
mat[0,:] # extract fst row
mat[1,:] #extract fst row
mat[:,3] #extract third column
mat[:,0] #extracts fst column

array([95,  4, 49, 76, 28, 71, 24,  8,  2, 83])

In [160]:
mat[0:3,0:4] # 3x4 matrix retrieved from mat

array([[95, 11, 81, 70],
       [ 4, 63, 40, 60],
       [49, 83,  8, 29]])